---
  ahoyapi: v2
  
  commands:
    up:
      usage: Build and start project.
      cmd: |
        docker-compose up -d "$@"

    stop:
      usage: Stops the project
      cmd: |
        docker-compose stop "$@"
  
    down:
      usage: Delete project (CAUTION).
      cmd: |
        if [ "$1" == "y" ]; then
          docker-compose down --volumes
        else
          ahoy confirm "Running this command will destroy your current site, database and build? Are you sure you didn't mean ahoy stop?" &&
          # Run this if confirm returns true
          docker-compose down --volumes ||
          # Run this if confirm returns false
          echo "OK, probably a wise choice..."
        fi
  
    build:
      usage: Build project.
      cmd: |
        docker-compose up -d --build "$@"

    cli:
      usage: Start a shell inside a container.
      cmd: docker-compose exec "$@" sh
    ps:
      usage: Check processes running inside the container.
      cmd: docker-compose ps
    logs:
      usage: View logs.
      cmd: docker-compose logs "$@"
    restart:
      usage: Restart the project.
      cmd: docker-compose restart "$@"
      