version: "3"

services:
  db:
    container_name: postgres
    build:
      context: postgres/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    network_mode: host

  solr:
    container_name: solr
    build:
      context: solr/
    isolation: default
    network_mode: host
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
  
  # datapusher:
  #   container_name: datapusher
  #   build: 
  #     context: datapusher/
  #   network_mode: host


  redis:
    container_name: redis
    image: redis:alpine
    network_mode: host

volumes:
  pg_data:
  solr_data:
