version: "3"

services:
  db:
    container_name: posgres
    build:
      context: postgres/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    network_mode: host
    ports:
      - "5432:5432"

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    network_mode: host
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine
    network_mode: host

volumes:
  pg_data:
  solr_data:
