version: "3"

services:
  db:
    container_name: dathere-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - dathere-pg_data:/var/lib/postgresql/data
    network_mode: host

  solr:
    container_name: dathere-solr
    build:
      context: solr/
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - dathere-solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: dathere-redis
    image: redis:alpine
    network_mode: host


volumes:
  dathere-pg_data:
  dathere-solr_data:
