version: "3"

services:
  db:
    container_name: ${PROJECT_NAME}-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      -${PROJECT_NAME}-pg_data:/var/lib/postgresql/data
    network_mode: host

  solr:
    container_name: ${PROJECT_NAME}-solr
    build:
      context: solr/
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ${PROJECT_NAME}-solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:alpine
    network_mode: host


volumes:
  ${PROJECT_NAME}-pg_data:
  ${PROJECT_NAME}-solr_data:
