version: "3"

services:
  db:
    container_name: ${PROJECT_NAME}-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  solr:
    container_name: ${PROJECT_NAME}-solr
    build:
      context: solr/
      dockerfile: Dockerfile
    ports:
      - "8983:8983"
    volumes:
      - type: volume
        source: solr_data
        target: /opt/solr/server/solr

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:alpine
    ports:
      - "6379:6379"

  mailcatcher:
    restart: on-failure
    image: haravich/fake-smtp-server
    ports:
    - "1080:1080"
    - "1025:1025"


volumes:
  pg_data:
    external: false
    name: ${PROJECT_NAME}-pg_data
  solr_data:
    external: false
    name: ${PROJECT_NAME}-solr_data
